# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fcs_pb2 as fcs__pb2
import usertag_pb2 as usertag__pb2
import mid_pb2 as mid__pb2
import uds_pb2 as uds__pb2
import amp_pb2 as amp__pb2
import wemedia_pb2 as wemedia__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs.proto',
  package='cs',
  syntax='proto2',
  serialized_pb=_b('\n\x08\x63s.proto\x12\x02\x63s\x1a\tfcs.proto\x1a\rusertag.proto\x1a\tmid.proto\x1a\tuds.proto\x1a\tamp.proto\x1a\rwemedia.proto\"\xa5\x02\n\x07ReqBody\x12\x1e\n\x08\x66\x63s_info\x18\x01 \x01(\x0b\x32\x0c.fcs.FcsInfo\x12&\n\x08uds_info\x18\x02 \x01(\x0b\x32\x14.Target.QueryReqBody\x12\x1e\n\x08mid_info\x18\x04 \x01(\x0b\x32\x0c.mid.ReqBody\x12\x10\n\x08str_uuid\x18\x05 \x01(\t\x12\"\n\x0cnew_uds_info\x18\x06 \x01(\x0b\x32\x0c.uds.ReqBody\x12(\n\ramp_query_req\x18\x07 \x01(\x0b\x32\x11.amp.QueryReqBody\x12*\n\x0e\x61mp_update_req\x18\x08 \x01(\x0b\x32\x12.amp.UpdateReqBody\x12&\n\x0cwemedia_info\x18\t \x01(\x0b\x32\x10.wemedia.ReqBody\"\xae\x02\n\x08RespBody\x12\x1e\n\x08\x66\x63s_info\x18\x01 \x01(\x0b\x32\x0c.fcs.FcsInfo\x12\'\n\x08uds_info\x18\x02 \x01(\x0b\x32\x15.Target.QueryRespBody\x12\x1f\n\x08mid_info\x18\x04 \x01(\x0b\x32\r.mid.RespBody\x12#\n\x0cnew_uds_info\x18\x05 \x01(\x0b\x32\r.uds.RespBody\x12*\n\x0e\x61mp_query_resp\x18\x06 \x01(\x0b\x32\x12.amp.QueryRespBody\x12,\n\x0f\x61mp_update_resp\x18\x07 \x01(\x0b\x32\x13.amp.UpdateRespBody\x12\'\n\x0cwemedia_info\x18\x08 \x01(\x0b\x32\x11.wemedia.RespBody\x12\x10\n\x08ret_code\x18\x63 \x01(\r')
  ,
  dependencies=[fcs__pb2.DESCRIPTOR,usertag__pb2.DESCRIPTOR,mid__pb2.DESCRIPTOR,uds__pb2.DESCRIPTOR,amp__pb2.DESCRIPTOR,wemedia__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQBODY = _descriptor.Descriptor(
  name='ReqBody',
  full_name='cs.ReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fcs_info', full_name='cs.ReqBody.fcs_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uds_info', full_name='cs.ReqBody.uds_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mid_info', full_name='cs.ReqBody.mid_info', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str_uuid', full_name='cs.ReqBody.str_uuid', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_uds_info', full_name='cs.ReqBody.new_uds_info', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amp_query_req', full_name='cs.ReqBody.amp_query_req', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amp_update_req', full_name='cs.ReqBody.amp_update_req', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wemedia_info', full_name='cs.ReqBody.wemedia_info', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=384,
)


_RESPBODY = _descriptor.Descriptor(
  name='RespBody',
  full_name='cs.RespBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fcs_info', full_name='cs.RespBody.fcs_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uds_info', full_name='cs.RespBody.uds_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mid_info', full_name='cs.RespBody.mid_info', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_uds_info', full_name='cs.RespBody.new_uds_info', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amp_query_resp', full_name='cs.RespBody.amp_query_resp', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amp_update_resp', full_name='cs.RespBody.amp_update_resp', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wemedia_info', full_name='cs.RespBody.wemedia_info', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='cs.RespBody.ret_code', index=7,
      number=99, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=689,
)

_REQBODY.fields_by_name['fcs_info'].message_type = fcs__pb2._FCSINFO
_REQBODY.fields_by_name['uds_info'].message_type = usertag__pb2._QUERYREQBODY
_REQBODY.fields_by_name['mid_info'].message_type = mid__pb2._REQBODY
_REQBODY.fields_by_name['new_uds_info'].message_type = uds__pb2._REQBODY
_REQBODY.fields_by_name['amp_query_req'].message_type = amp__pb2._QUERYREQBODY
_REQBODY.fields_by_name['amp_update_req'].message_type = amp__pb2._UPDATEREQBODY
_REQBODY.fields_by_name['wemedia_info'].message_type = wemedia__pb2._REQBODY
_RESPBODY.fields_by_name['fcs_info'].message_type = fcs__pb2._FCSINFO
_RESPBODY.fields_by_name['uds_info'].message_type = usertag__pb2._QUERYRESPBODY
_RESPBODY.fields_by_name['mid_info'].message_type = mid__pb2._RESPBODY
_RESPBODY.fields_by_name['new_uds_info'].message_type = uds__pb2._RESPBODY
_RESPBODY.fields_by_name['amp_query_resp'].message_type = amp__pb2._QUERYRESPBODY
_RESPBODY.fields_by_name['amp_update_resp'].message_type = amp__pb2._UPDATERESPBODY
_RESPBODY.fields_by_name['wemedia_info'].message_type = wemedia__pb2._RESPBODY
DESCRIPTOR.message_types_by_name['ReqBody'] = _REQBODY
DESCRIPTOR.message_types_by_name['RespBody'] = _RESPBODY

ReqBody = _reflection.GeneratedProtocolMessageType('ReqBody', (_message.Message,), dict(
  DESCRIPTOR = _REQBODY,
  __module__ = 'cs_pb2'
  # @@protoc_insertion_point(class_scope:cs.ReqBody)
  ))
_sym_db.RegisterMessage(ReqBody)

RespBody = _reflection.GeneratedProtocolMessageType('RespBody', (_message.Message,), dict(
  DESCRIPTOR = _RESPBODY,
  __module__ = 'cs_pb2'
  # @@protoc_insertion_point(class_scope:cs.RespBody)
  ))
_sym_db.RegisterMessage(RespBody)


# @@protoc_insertion_point(module_scope)
