# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fid.proto',
  package='fid',
  syntax='proto2',
  serialized_pb=_b('\n\tfid.proto\x12\x03\x66id\"n\n\x07\x46idInfo\x12,\n\rrpt_fid_value\x18\x01 \x03(\x0b\x32\x15.fid.FidInfo.FidValue\x1a\x35\n\x08\x46idValue\x12\x13\n\x0bstr_freq_id\x18\x01 \x01(\t\x12\x14\n\x0cuint32_value\x18\x02 \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FIDINFO_FIDVALUE = _descriptor.Descriptor(
  name='FidValue',
  full_name='fid.FidInfo.FidValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str_freq_id', full_name='fid.FidInfo.FidValue.str_freq_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uint32_value', full_name='fid.FidInfo.FidValue.uint32_value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=128,
)

_FIDINFO = _descriptor.Descriptor(
  name='FidInfo',
  full_name='fid.FidInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rpt_fid_value', full_name='fid.FidInfo.rpt_fid_value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FIDINFO_FIDVALUE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=128,
)

_FIDINFO_FIDVALUE.containing_type = _FIDINFO
_FIDINFO.fields_by_name['rpt_fid_value'].message_type = _FIDINFO_FIDVALUE
DESCRIPTOR.message_types_by_name['FidInfo'] = _FIDINFO

FidInfo = _reflection.GeneratedProtocolMessageType('FidInfo', (_message.Message,), dict(

  FidValue = _reflection.GeneratedProtocolMessageType('FidValue', (_message.Message,), dict(
    DESCRIPTOR = _FIDINFO_FIDVALUE,
    __module__ = 'fid_pb2'
    # @@protoc_insertion_point(class_scope:fid.FidInfo.FidValue)
    ))
  ,
  DESCRIPTOR = _FIDINFO,
  __module__ = 'fid_pb2'
  # @@protoc_insertion_point(class_scope:fid.FidInfo)
  ))
_sym_db.RegisterMessage(FidInfo)
_sym_db.RegisterMessage(FidInfo.FidValue)


# @@protoc_insertion_point(module_scope)
