# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mid.proto',
  package='mid',
  syntax='proto2',
  serialized_pb=_b('\n\tmid.proto\x12\x03mid\"\x16\n\x07ReqBody\x12\x0b\n\x03mid\x18\x01 \x02(\t\"7\n\x08RespBody\x12\x0c\n\x04\x66lag\x18\x01 \x02(\x07\x12\n\n\x02qq\x18\x02 \x02(\x06\x12\x11\n\tdevice_id\x18\x03 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQBODY = _descriptor.Descriptor(
  name='ReqBody',
  full_name='mid.ReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mid', full_name='mid.ReqBody.mid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=40,
)


_RESPBODY = _descriptor.Descriptor(
  name='RespBody',
  full_name='mid.RespBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='mid.RespBody.flag', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qq', full_name='mid.RespBody.qq', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='mid.RespBody.device_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['ReqBody'] = _REQBODY
DESCRIPTOR.message_types_by_name['RespBody'] = _RESPBODY

ReqBody = _reflection.GeneratedProtocolMessageType('ReqBody', (_message.Message,), dict(
  DESCRIPTOR = _REQBODY,
  __module__ = 'mid_pb2'
  # @@protoc_insertion_point(class_scope:mid.ReqBody)
  ))
_sym_db.RegisterMessage(ReqBody)

RespBody = _reflection.GeneratedProtocolMessageType('RespBody', (_message.Message,), dict(
  DESCRIPTOR = _RESPBODY,
  __module__ = 'mid_pb2'
  # @@protoc_insertion_point(class_scope:mid.RespBody)
  ))
_sym_db.RegisterMessage(RespBody)


# @@protoc_insertion_point(module_scope)
