# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uds.proto',
  package='uds',
  syntax='proto2',
  serialized_pb=_b('\n\tuds.proto\x12\x03uds\"\xd2\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03sex\x18\x02 \x01(\r\x12\x0b\n\x03\x61ge\x18\x03 \x01(\r\x12\r\n\x05scene\x18\x04 \x01(\r\x12\x0c\n\x04\x61rea\x18\x05 \x01(\r\x12\x0b\n\x03job\x18\x06 \x01(\r\x12\x11\n\teducation\x18\x07 \x01(\r\x12\x0e\n\x06income\x18\x08 \x01(\r\x12\x1e\n\x03tag\x18\t \x03(\x0b\x32\x11.uds.UserInfo.Tag\x1a\x33\n\x03Tag\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x10\n\x08priority\x18\x02 \x01(\r\x12\x0c\n\x04time\x18\x03 \x01(\r\"\"\n\x07ReqBody\x12\x0b\n\x03uin\x18\x01 \x01(\x04\x12\n\n\x02\x66\x64\x18\x02 \x01(\x07\"W\n\x08RespBody\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x07\x12\x0b\n\x03uin\x18\x02 \x01(\x04\x12\n\n\x02\x66\x64\x18\x03 \x01(\x07\x12 \n\tvUserInfo\x18\x04 \x03(\x0b\x32\r.uds.UserInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERINFO_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='uds.UserInfo.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='uds.UserInfo.Tag.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='uds.UserInfo.Tag.priority', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='uds.UserInfo.Tag.time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=229,
)

_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='uds.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='uds.UserInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='uds.UserInfo.sex', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='uds.UserInfo.age', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene', full_name='uds.UserInfo.scene', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='uds.UserInfo.area', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job', full_name='uds.UserInfo.job', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='education', full_name='uds.UserInfo.education', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='income', full_name='uds.UserInfo.income', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='uds.UserInfo.tag', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERINFO_TAG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=229,
)


_REQBODY = _descriptor.Descriptor(
  name='ReqBody',
  full_name='uds.ReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='uds.ReqBody.uin', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fd', full_name='uds.ReqBody.fd', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=265,
)


_RESPBODY = _descriptor.Descriptor(
  name='RespBody',
  full_name='uds.RespBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='uds.RespBody.err_code', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uin', full_name='uds.RespBody.uin', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fd', full_name='uds.RespBody.fd', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vUserInfo', full_name='uds.RespBody.vUserInfo', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=354,
)

_USERINFO_TAG.containing_type = _USERINFO
_USERINFO.fields_by_name['tag'].message_type = _USERINFO_TAG
_RESPBODY.fields_by_name['vUserInfo'].message_type = _USERINFO
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['ReqBody'] = _REQBODY
DESCRIPTOR.message_types_by_name['RespBody'] = _RESPBODY

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(

  Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
    DESCRIPTOR = _USERINFO_TAG,
    __module__ = 'uds_pb2'
    # @@protoc_insertion_point(class_scope:uds.UserInfo.Tag)
    ))
  ,
  DESCRIPTOR = _USERINFO,
  __module__ = 'uds_pb2'
  # @@protoc_insertion_point(class_scope:uds.UserInfo)
  ))
_sym_db.RegisterMessage(UserInfo)
_sym_db.RegisterMessage(UserInfo.Tag)

ReqBody = _reflection.GeneratedProtocolMessageType('ReqBody', (_message.Message,), dict(
  DESCRIPTOR = _REQBODY,
  __module__ = 'uds_pb2'
  # @@protoc_insertion_point(class_scope:uds.ReqBody)
  ))
_sym_db.RegisterMessage(ReqBody)

RespBody = _reflection.GeneratedProtocolMessageType('RespBody', (_message.Message,), dict(
  DESCRIPTOR = _RESPBODY,
  __module__ = 'uds_pb2'
  # @@protoc_insertion_point(class_scope:uds.RespBody)
  ))
_sym_db.RegisterMessage(RespBody)


# @@protoc_insertion_point(module_scope)
