# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usertag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usertag.proto',
  package='Target',
  syntax='proto2',
  serialized_pb=_b('\n\rusertag.proto\x12\x06Target\"\xd5\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03sex\x18\x02 \x01(\r\x12\x0b\n\x03\x61ge\x18\x03 \x01(\r\x12\r\n\x05scene\x18\x04 \x01(\r\x12\x0c\n\x04\x61rea\x18\x05 \x01(\r\x12\x0b\n\x03job\x18\x06 \x01(\r\x12\x11\n\teducation\x18\x07 \x01(\r\x12\x0e\n\x06income\x18\x08 \x01(\r\x12!\n\x03tag\x18\t \x03(\x0b\x32\x14.Target.UserInfo.Tag\x1a\x33\n\x03Tag\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x10\n\x08priority\x18\x02 \x01(\r\x12\x0c\n\x04time\x18\x03 \x01(\r\"]\n\x0cQueryReqBody\x12\x0b\n\x03uin\x18\x01 \x02(\x07\x12\x0e\n\x06\x63li_ip\x18\x02 \x02(\x07\x12\x10\n\x08\x63li_port\x18\x03 \x02(\x07\x12\x12\n\nv_req_code\x18\x04 \x03(\x07\x12\n\n\x02\x66\x64\x18\x05 \x02(\x07\"\x8d\x01\n\rQueryRespBody\x12\x0b\n\x03uin\x18\x01 \x02(\x07\x12\x30\n\x08vRspCode\x18\x02 \x03(\x0b\x32\x1e.Target.QueryRespBody.RespCode\x1a=\n\x08RespCode\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x07\x12\x13\n\x0bupdate_time\x18\x02 \x02(\x07\x12\x0e\n\x06weight\x18\x03 \x02(\x07\",\n\x07\x45rrBody\x12\x10\n\x08\x65rr_code\x18\x01 \x02(\x05\x12\x0f\n\x07\x65rr_msg\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERINFO_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='Target.UserInfo.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Target.UserInfo.Tag.code', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='Target.UserInfo.Tag.priority', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='Target.UserInfo.Tag.time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=239,
)

_USERINFO = _descriptor.Descriptor(
  name='UserInfo',
  full_name='Target.UserInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Target.UserInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sex', full_name='Target.UserInfo.sex', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='Target.UserInfo.age', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene', full_name='Target.UserInfo.scene', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area', full_name='Target.UserInfo.area', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job', full_name='Target.UserInfo.job', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='education', full_name='Target.UserInfo.education', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='income', full_name='Target.UserInfo.income', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='Target.UserInfo.tag', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_USERINFO_TAG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=239,
)


_QUERYREQBODY = _descriptor.Descriptor(
  name='QueryReqBody',
  full_name='Target.QueryReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='Target.QueryReqBody.uin', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cli_ip', full_name='Target.QueryReqBody.cli_ip', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cli_port', full_name='Target.QueryReqBody.cli_port', index=2,
      number=3, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_req_code', full_name='Target.QueryReqBody.v_req_code', index=3,
      number=4, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fd', full_name='Target.QueryReqBody.fd', index=4,
      number=5, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=334,
)


_QUERYRESPBODY_RESPCODE = _descriptor.Descriptor(
  name='RespCode',
  full_name='Target.QueryRespBody.RespCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Target.QueryRespBody.RespCode.code', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='Target.QueryRespBody.RespCode.update_time', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='Target.QueryRespBody.RespCode.weight', index=2,
      number=3, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=478,
)

_QUERYRESPBODY = _descriptor.Descriptor(
  name='QueryRespBody',
  full_name='Target.QueryRespBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uin', full_name='Target.QueryRespBody.uin', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vRspCode', full_name='Target.QueryRespBody.vRspCode', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUERYRESPBODY_RESPCODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=478,
)


_ERRBODY = _descriptor.Descriptor(
  name='ErrBody',
  full_name='Target.ErrBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='Target.ErrBody.err_code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='Target.ErrBody.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=524,
)

_USERINFO_TAG.containing_type = _USERINFO
_USERINFO.fields_by_name['tag'].message_type = _USERINFO_TAG
_QUERYRESPBODY_RESPCODE.containing_type = _QUERYRESPBODY
_QUERYRESPBODY.fields_by_name['vRspCode'].message_type = _QUERYRESPBODY_RESPCODE
DESCRIPTOR.message_types_by_name['UserInfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['QueryReqBody'] = _QUERYREQBODY
DESCRIPTOR.message_types_by_name['QueryRespBody'] = _QUERYRESPBODY
DESCRIPTOR.message_types_by_name['ErrBody'] = _ERRBODY

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), dict(

  Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
    DESCRIPTOR = _USERINFO_TAG,
    __module__ = 'usertag_pb2'
    # @@protoc_insertion_point(class_scope:Target.UserInfo.Tag)
    ))
  ,
  DESCRIPTOR = _USERINFO,
  __module__ = 'usertag_pb2'
  # @@protoc_insertion_point(class_scope:Target.UserInfo)
  ))
_sym_db.RegisterMessage(UserInfo)
_sym_db.RegisterMessage(UserInfo.Tag)

QueryReqBody = _reflection.GeneratedProtocolMessageType('QueryReqBody', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQBODY,
  __module__ = 'usertag_pb2'
  # @@protoc_insertion_point(class_scope:Target.QueryReqBody)
  ))
_sym_db.RegisterMessage(QueryReqBody)

QueryRespBody = _reflection.GeneratedProtocolMessageType('QueryRespBody', (_message.Message,), dict(

  RespCode = _reflection.GeneratedProtocolMessageType('RespCode', (_message.Message,), dict(
    DESCRIPTOR = _QUERYRESPBODY_RESPCODE,
    __module__ = 'usertag_pb2'
    # @@protoc_insertion_point(class_scope:Target.QueryRespBody.RespCode)
    ))
  ,
  DESCRIPTOR = _QUERYRESPBODY,
  __module__ = 'usertag_pb2'
  # @@protoc_insertion_point(class_scope:Target.QueryRespBody)
  ))
_sym_db.RegisterMessage(QueryRespBody)
_sym_db.RegisterMessage(QueryRespBody.RespCode)

ErrBody = _reflection.GeneratedProtocolMessageType('ErrBody', (_message.Message,), dict(
  DESCRIPTOR = _ERRBODY,
  __module__ = 'usertag_pb2'
  # @@protoc_insertion_point(class_scope:Target.ErrBody)
  ))
_sym_db.RegisterMessage(ErrBody)


# @@protoc_insertion_point(module_scope)
